# Docker Compose configuration for setting up a local testing environment.
# This includes a PostgreSQL database, Adminer for database management, and Redis for caching.

networks:
  development-network:
    driver: bridge

services:
  # PostgreSQL database service
  # https://hub.docker.com/_/postgres
  postgresql-database:
    container_name: postgresql-database
    image: postgres:16.4-alpine3.20@sha256:492898505cb45f9835acc327e98711eaa9298ed804e0bb36f29e08394229550d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coursemetricsDB
    ports:
      - 5433:5432 # Exposes the database on localhost:5433
    networks:
      - development-network

  # Adminer service for database management
  # Adminer provides a simple web UI for interacting with the PostgreSQL database.
  # https://hub.docker.com/_/adminer
  adminer:
    container_name: adminer
    image: adminer@sha256:34d37131366c5aa84e1693dbed48593ed6f95fb450b576c1a7a59d3a9c9e8802
    restart: always
    ports:
      - 8080:8080 # Exposes Adminer UI on localhost:8080
    networks:
      - development-network

  # Redis service for caching or message broker
  # https://hub.docker.com/_/redis
  redis:
    container_name: redis
    image: redis:7.4.1-alpine@sha256:c1e88455c85225310bbea54816e9c3f4b5295815e6dbf80c34d40afc6df28275
    restart: always
    ports:
      - 6379:6379 # Exposes Redis on localhost:6379
    networks:
      - development-network
